apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: {{ .Values.imageRegistry }}/deploytest:{{ .Values.moduleVersion }}
          imagePullPolicy: Always
          ports:
            - name: {{ .Values.app }}-port
              containerPort: {{ .Values.servicePort }}
          volumeMounts:
            - name: {{ .Values.app }}-volume
              mountPath: /build
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.servicePort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.servicePort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: {{ .Values.app }}-volume
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: DirectoryOrCreate