apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
    - name: {{ .Values.app }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}