apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app }}
  ports:
    - name: {{ .Values.app }}-port
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.consumeBatch.externalName }}
spec:
  type: ExternalName
  externalName: consumebatch.consumebatch.svc.cluster.local