replicas: 1
app: deploytest
consumeBatch:
  externalName: consumebatch-ext
  servicePort: 8080
namespace: deploytest

imageRegistry: registry.pastelcloud.store

moduleVersion: 0.1.2

servicePort: 443

subDomain: "cc"
domain: "pastelcloud.store"

secretName: deploytest-clusterissue

persistence:
  hostPath: /data/deploytest

livenessProbe:
  path: /

readinessProbe:
  path: /