app: deploytest

namespace: deploytest

imageRegistry: localhost:32500

moduleVersion: 0.1.0

servicePort0: 443
servicePort1: 443

subDomain: "deploytest"
domain: "pastelcloud.store"

secretName: letsencrypt-prod

persistence:
  hostPath: /data/deploytest

livenessProbe:
  path: /

readinessProbe:
  path: /