app: deploytest

namespace: deploytest

imageRegistry: localhost:32500

moduleVersion: 0.0.9

servicePort0: 80
servicePort1: 443

subDomain: "deploytest"
domain: "pastelcloud.store"

secretName: letsencrypt-prod

persistence:
  hostPath: /data/deploytest

livenessProbe:
  path: /

readinessProbe:
  path: /