app: deploytest

namespace: deploytest

imageRegistry: localhost:32500

moduleVersion: 0.1.2

servicePort: 443

subDomain: "deploytest"
domain: "pastelcloud.store"

secretName: deploytest-clusterissue

persistence:
  hostPath: /data/deploytest

livenessProbe:
  path: /

readinessProbe:
  path: /