app: deploytest

namespace: deploytest

imageRegistry: localhost:32500

moduleVersion: 0.0.2

servicePort: 48880

subDomain: "deploytest"
domain: "pastelcloud.store"

secretName: letsencrypt-prod

persistence:
  hostPath: /data/deploytest

livenessProbe:
  path: /

readinessProbe:
  path: /