app: deploytest
consumeBatch:
  externalName: consumebatch-ext
  servicePort: 8080
namespace: deploytest

imageRegistry: registry.pastelcloud.shop

moduleVersion: 0.1.2

servicePort: 443

subDomain: "deploytest"
domain: "pastelcloud.shop"

secretName: deploytest-clusterissue

persistence:
  hostPath: /data/deploytest

livenessProbe:
  path: /

readinessProbe:
  path: /